// server.js — Local HTTPS server for testing the RCC Mail add-in
//
// Why HTTPS? Office Add-ins require HTTPS even for localhost.
// This server uses certs generated by office-addin-dev-certs (Microsoft tool)
// which are trusted by Windows automatically so Outlook accepts them.
//
// Usage:
//   1. npm install                     (first time only)
//   2. npm run install-certs           (first time only — installs trusted dev certs)
//   3. npm start                       (starts this server on port 3000)
//
// Then sideload manifest.xml in Outlook — see INSTALL.md for steps.

const https   = require("https");
const fs      = require("fs");
const path    = require("path");
const os      = require("os");

const PORT = 3000;

// MIME types for every file extension we serve
const MIME = {
  ".html": "text/html; charset=utf-8",
  ".js":   "application/javascript; charset=utf-8",
  ".css":  "text/css; charset=utf-8",
  ".json": "application/json",
  ".png":  "image/png",
  ".ico":  "image/x-icon",
  ".svg":  "image/svg+xml",
};

// office-addin-dev-certs stores certs here by default
const CERTS_DIR = path.join(os.homedir(), ".office-addin-dev-certs");

function loadCerts() {
  const keyPath  = path.join(CERTS_DIR, "localhost.key");
  const certPath = path.join(CERTS_DIR, "localhost.crt");

  if (!fs.existsSync(keyPath) || !fs.existsSync(certPath)) {
    console.error("\n[ERROR] Dev certificates not found.");
    console.error("  Run: npm run install-certs");
    console.error("  Then restart: npm start\n");
    process.exit(1);
  }

  return {
    key:  fs.readFileSync(keyPath),
    cert: fs.readFileSync(certPath),
  };
}

// Serve a static file, or return 404
function serveFile(res, filePath) {
  // Security: reject any path that tries to escape the project folder
  const safePath = path.resolve(__dirname, filePath);
  if (!safePath.startsWith(__dirname)) {
    res.writeHead(403);
    res.end("Forbidden");
    return;
  }

  if (!fs.existsSync(safePath)) {
    res.writeHead(404);
    res.end("Not found: " + filePath);
    return;
  }

  const ext         = path.extname(safePath).toLowerCase();
  const contentType = MIME[ext] || "application/octet-stream";

  res.writeHead(200, {
    "Content-Type":                contentType,
    "Access-Control-Allow-Origin": "*",       // needed so Outlook can load the pages
    "Cache-Control":               "no-cache",
  });
  res.end(fs.readFileSync(safePath));
}

const server = https.createServer(loadCerts(), function (req, res) {
  // Strip query string, decode %20 etc.
  const urlPath = decodeURIComponent(req.url.split("?")[0]);

  // Default to taskpane if root is requested
  const filePath = urlPath === "/" ? "src/taskpane.html" : urlPath.replace(/^\//, "");

  serveFile(res, filePath);
});

server.listen(PORT, function () {
  console.log("\n✅ RCC Mail add-in server running:");
  console.log("   https://localhost:" + PORT + "/src/taskpane.html");
  console.log("\n   Open Outlook → sideload manifest.xml → see INSTALL.md");
  console.log("   Press Ctrl+C to stop.\n");
});
